branch-defaults:
  develop:
    environment: deploy-docker-dev
  main:
    environment: deploy-docker-dev
    group_suffix: null
global:
  application_name: deploy-docker
  branch: null
  default_ec2_keyname: EC2 Tutorial
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
